CREATE DATABASE Thach_db;
USE Thach_db;

CREATE TABLE sugoi (
    CustomerID INT PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Age INT CHECK (Age > 0)
);

ALTER TABLE sugoi
MODIFY FullName VARCHAR(100) NOT NULL,
MODIFY Email VARCHAR(100) NOT NULL UNIQUE,
MODIFY Age INT;