CREATE DATABASE library;
USE library;

CREATE TABLE BOOK(
	bookId INT PRIMARY KEY,
    bookName VARCHAR(200) NOT NULL,
    bookNumber INT NOT NULL CHECK (bookNumber >= 0),
    bookPrice DECIMAL(2,1) NOT NULL DEFAULT 5000
);

ALTER TABLE BOOK
MODIFY bookId INT AUTO_INCREMENT;

ALTER TABLE BOOK
ADD COLUMN createdBook DATE;

CREATE TABLE  BORROW_BOOKS(
	borrowId INT PRIMARY KEY,
	bookId INT UNIQUE,
	FOREIGN KEY (bookId) REFERENCES BOOK(bookId),
    borrowDate DATE NOT NULL
);
